
INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica')
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica') 
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica') 
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa')
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia') 
INSERT INTO regiones (id, nombre) VALUES (6, 'Africa')
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía') 
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida') 
INSERT INTO clientes (region_id, nombre, apellido, email, createAt) VALUES (1, 'Richard', 'Paz', 'richard@unicauca.edu.co' , '2024-01-01') 
INSERT INTO clientes (region_id, nombre, apellido, email, createAt) VALUES (2, 'Steve', 'Jobs', 'sjobs@unicauca.edu.co', '2024-01-01') 
INSERT INTO clientes (region_id, nombre, apellido, email, createAt) VALUES (4, 'Linus', 'Torvalds', 'linus.torvalds@gmail.co', '2024-01-01')
